services:
  backend:
    build: 
      context: ./backend
    ports:
      - "4000:4000"
    networks:
      - workout-logger-network
  frontend:
    build: 
      context: ./frontend
    ports:
      - "80:80"
    networks:
      - workout-logger-network
networks:
  workout-logger-network: